config/routes.rb
Remotecontroll::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => "interfaces#show", :id => 1

  get "screen_app_communication/led"
  get "screen_app_communication/keyDown"
  get "screen_app_communication/keyUp"
  get "screen_app_communication/newUser"
  match 'pusher/auth' => 'screen_app_communication#auth'

  resources :interfaces
  resources :screen_apps

end

app/models/screen_app.rb
# == Schema Information
#
# Table name: screen_apps
#
#  id              :integer         primary key
#  name            :string(255)
#  url             :string(255)
#  logs_arrows     :boolean
#  created_at      :timestamp
#  updated_at      :timestamp
#  user_id         :integer
#  register_arrows :boolean
#  description     :text
#

class ScreenApp < ActiveRecord::Base
  after_update :save_interfaces
  
  validates :name,  :presence => true,
                    :length   => { :minimum => 3,
                                   :maximum => 40 },
                    :uniqueness => true
  validates :url,   :presence => true,
                    :uniqueness => true
                    
  validates_format_of :url, :with => URI::regexp(%w(http https))
  
  validates :user_id, :presence => true
  
  validates_associated :interface
  
  belongs_to :user
  
  has_many :interfaces, :dependent => :destroy
  
  def new_interface_attributes=(interface_attributes)
    interface_attributes.each do |attributes|
      interfaces.build(attributes)
    end
  end
  
  def existing_interface_attributes=(interface_attributes)
    interfaces.reject(&:new_record?).each do |interface|
      interfaces = interface_attributes[interface.id.to_s]
      if attributes
        interface.attributes = attributes
      else
        interfaces.delete(interface)
      end
    end
  end
  
  def save_interfaces
    interfaces.each do |interface|
      interface.save(false)
    end
  end
end

app/controllers/screen_apps_controller.rb
class ScreenAppsController < ApplicationController

  before_filter :find_screen_app, :only => [:edit, :show, :destroy]
  before_filter :authenticate_user!, :only => [:new, :create, :update, :destroy]
  before_filter :authorized_user, :only => [:destroy, :update] 
  
  def new
    @screen_app = ScreenApp.new
    @screen_app.interfaces.build
  end
  
  def index
    @screen_apps = ScreenApp.all
  end
  
  def edit
  end

  def create
    @screen_app = ScreenApp.new(params[:screen_app])
    @screen_app.user = current_user
    
    respond_to do |format|
      if @screen_app.save
        format.html { redirect_to(@screen_app,
                      :notice => 'Your app has been created! Now you should upload an interface, or select an alternative input method.') }
        format.xml  { render :xml => @interface,
                      :status => :created, :location => @interface }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interface.errors,
                      :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    params[:screen_app][:existing_interfaces_attributes] ||= {}

    @screen_app = ScreenApp.find(params[:id])
    if @screen_app.update_attributes(params[:screen_app])
      flash[:notice] = "Successfully updated screen_app and interfaces."
      redirect_to screen_app_path(@screen_app)
    else
      render :action => 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @screen_app.destroy
    redirect_back_or root_path
  end
  
  private
  
    def find_screen_app
      @screen_app = ScreenApp.find(params[:id])
    end

    def authorized_user
      @screen_app = current_user.screen_apps.find_by_id(params[:id])
      redirect_to root_path if @screen_app.nil?
    end
end

app/helpers/screen_apps_helper.rb
module ScreenAppsHelper
  def add_interface_link(name)
    #link_to_function name, @pages do |page|
    #  page.insert_html :bottom, :interfaces, :partial => 'interface' , :object => Interface.new
    #end
    link_to name, "#", "" => h(render(:partial => 'interface', :object => Interface.new)), :class => 'add_interface'
  end
end

app/views/screen_apps/_form.html.erb
<%= form_for @screen_app do |f| %>
	<fieldset>
		<legend>Basic info</legend>
		<div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>
	  
	  <div class="field">
	    <%= f.label :url %><br />
	    <%= f.text_field :url %>
	  </div>
	  
	  <div class="field">
	    <%= f.label :description %><br />
	    <%= f.text_area :description %>
	  </div>
	</fieldset>
	
	<fieldset>
  	<legend>Input types</legend>	
	  <div class="field">
	    <%= f.label :register_arrows %>
	    <%= f.check_box :register_arrows %>
	  </div>
	  
	  <div id="interfaces">
	  	<%= render :partial => 'interface', :collection => @screen_app.interfaces %>
	  </div>
	  <%= add_interface_link "Add a TouchOSC interface" %>
	</fieldset>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screen_apps/_interface.html.erb
<div class="interface">
	<% new_or_existing = interface.new_record? ? 'new' : 'existing' %>
	<% prefix = "screen_app[#{new_or_existing}_interface_attributes][]" %>
	<% fields_for prefix, interface do |interface_form| %>
	<p>
		Interface: <%= interface_form.text_field :name %>, <%= interface_form.file_field :json %>
		<%= link_to "remove" , "#", :class => 'remove_task' %>
	</p>
	<% end %>
</div>

app/views/screen_apps/_screen_app_form.html.erb
<%= form_for(@screen_app) do |f| %>
	<fieldset>
		<legend>Basic info</legend>
		<div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>
	  
	  <div class="field">
	    <%= f.label :url %><br />
	    <%= f.text_field :url %>
	  </div>
	  
	  <div class="field">
	    <%= f.label :description %><br />
	    <%= f.text_area :description %>
	  </div>
	</fieldset>
	
	<fieldset>
  	<legend>Input types</legend>	
	  <div class="field">
	    <%= f.label :register_arrows %>
	    <%= f.check_box :register_arrows %>
	  </div>
	</fieldset>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screen_apps/edit.html.erb
<h1>Submit a new app</h1>

<% if @screen_app.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@screen_app.errors.count, "error") %> 
        prohibited this app from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @screen_app.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render "screen_apps/form" %>

<%= link_to 'Back', screen_apps_path %> | <%= link_to "Delete this app",
	  			@screen_app,
	  			:method => :delete,
	       	:confirm => "You sure very sure?" %>

app/views/screen_apps/index.html.erb
<h2>Existing applications</h2>
<% if @screen_apps %>
	<ul>
	<% @screen_apps.each do |screen_app| %>
  	<li><b><%= screen_app.name %></b>
  		<% if current_user == (screen_app.user) %> |
	  		<%= link_to 'Edit', edit_screen_app_path(screen_app) %>
	     <% end %>
    </li>
	<% end %>
	</ul>
<% end %>

<% if user_signed_in? %>
	<%= link_to 'Add a new app!', new_screen_app_path() %>
<% end %>

app/views/screen_apps/new.html.erb
<h1>Submit a new app</h1>

<% if @screen_app.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@screen_app.errors.count, "error") %> 
        prohibited this app from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @screen_app.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render "screen_apps/form" %>

app/views/screen_apps/show.html.erb
<% if @screen_app %>
  <h1><%= @screen_app.name %></h1>
  <p>The app: <%= @screen_app.url %></p>
  <p>The interfaces: </p>
  <p><%= link_to 'Edit', edit_screen_app_path(@screen_app) %></p>
<% end %>